package Performance;

import io.FileManager;

public class TestSupport {
    private static String blogPost = "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Sinänsä taloudellinen toimeliaisuus on vain yksi osa ihmisten hyvinvointia ja yhteiskunnan toimintaa, mutta sen merkitystä usein vähätellään tavoilla joka ei oikein kestä tarkempaa tarkastelua. Ei ole tavatonta, että leppoisan älyllisessä, siistissä sisätyössä työskentelevä downshiftaaja kritisoi \"rahan valtaa\" ja ihmettelee miksi muut eivät elä kuin hän, rennosti ja \"rahasta piittaamatta\". Mediassa ja päivänpolitiikassa pyöriteltävät aiheet vaikuttavat helposti pikkumaisilta, ja sellaisiksi ne leimaantuvatkin kun puhetapa ottaa vallan.  \n" +
            "\n" +
            "Raha tulee pankista, ja keskuspankki lainaa rahaa ilmaiseksi pankille joka sitten tyrkyttää sitä ihmisille. Tämä on tietenkin totta prima facie. Yrittäessään systeeminäkökulman avartamista itselleen, tilannetta analysoiva idealisti -- vaikka tämä karakterisointi onkin vähän väärä -- sitten liimaa päälle koko joukon erilaisia sarjakuvamaisia uhkakuvia, kuten luonnon raiskaamista, eläinten kaltoinkohtelua jne, ja laiskana ihmisenä niputtaa kaiken tämän \"kapitalistisen järjestelmän\" väistämättömäksi tuotteeksi. Siinä onkin sitten jo hyvä taputella tuon samaisen paholaisen tuottaman järjestelmän lihottamaa pötsiä itsetyytyväisenä ja uskoa tietävänsä paremmin.\n" +
            "\n" +
            "Todellisuus on kuitenkin olemassa tämän kuplan ulkopuolella. Maanviljelijä kylvää pellot keväällä ja niittä viljan loppukesästä. Tähkäpäistä jauhetaan myllyssä jauhoa ja hiusverkkoon pukeutunut leipuri sen leipoo, oli sitten kyse höttöisestä vehnästä tai tummasta kokojyvästä jota mutustellaan paksusuolen syövän pelossa.\n" +
            "\n" +
            "Karuinta tässä todellisuudessa tietenkin on, että ei oikeastaan ole mitään systeemiä. Ei ole isoveljeä joka oikeasti valvoisi. Terence McKennan sanoin \"The real truth that dares not speak its name is that no one is in control\". Kukaan ei istu puikoissa, valvomo on tyhjä, eikä matrixin keskellä ole salaista huonetta jossa istuu kaiken suunnitellut arkkitehti.\n" +
            "\n" +
            "Sarjakuvamainen käsitys systeemistä, oli kyse sitten pahasta hallituksesta joka yrittää kontrolloida meitä taudin varjolla tai kapitalistisesta salaliitosta, joka houkuttelee ihmiset oravanpyörään tuottamaan lisää kuvitteellista rahaa miljardöörien pohjattomaan kirstuun, on vain lohduttava valhe jota kerromme itsellemme. Evoluutioantropologi Elaine Morgania löyhästi siteeraten, tutkiessamme ihmisten muodostamia yhteiskuntia vastataksemme  kysymykseen \"Mitä ihmiset tahtovat?\", ainoa löytämämme vastaus tuntuu olevan \"lisää\".  Kun kädellinen nappaa kiinni herkusta, se ei päästä irti. Legenda kertoo että apinan voi pyydystää niin että laittaa häkkiin banaanin siten, että se ei mahdu häkin kaltereiden välistä ulos. Kun apina tarraa banaaniin kiinni, se ei saa enää kättään häkistä ulos ja näin se jää vangiksi, sillä se ei osaa irrottaa saaliistaan.\n" +
            "\n" +
            "En ole fatalisti, enkä myöskään toivo sen kummemmin ihmiskunnan turmiota kuten vaikkapa hiljattain edesmennyt Pentti Linkola aikanaan. Elämme nyt aikoja jotka koettelevat itse kunkin uskoa siihen miten hyvin tämä hallitsematon systeemi toimii. Mutta tässä onkin nyt yksi olennainen asia. Se systeemi kaikkine mielikuvineen ja ihmetyksen aiheneenkin, on lopulta vain osiensa summa. Kaikki emergenssi jota me uskomme siinä näkevämme, on lopulta vain kuvitelmaamme. Todellinen Matrix ei ole mikään markkinamiesten syöttämä valhekuva, se ei ole salaliitto jota Bilderberg-kokouksissa ylläpidetään. Se ei ole hallituksen salajuoni, ei vapaamuurareiden, Perussuomalaisten, liberaalien, temppeliherrojen tai kenenkään muunkaan salaisissa kokouksissa orkestroima suuri huijaus.\n" +
            "\n" +
            "Todellinen, pelottava totuus on, ettei sitä ole laisinkaan. Me kuvittelemme sen, koska haluamme uskoa että jos tilanne menee oikein pahaksi niin joku kyllä puuttuu asiaan. Emme ehkä tiedä kuka se joku on, mutta moni meistä uskoo että joku kyllä jossain tulee apuun ennen kuin kaikki romahtaa.\n" +
            "\n" +
            "Mutta ketään ei tule. Olemme omillamme. Ja se on hyvä. Elämme kovia aikoja, ystävä hyvä.\n" +
            "\n" +
            "Kun opiskelin aikanaan kansantaloustiedettä, eräs luennoija -- en sano \"legendaarinen\", koska en tunne kulttuuria vaikka mieli tekisi -- Hannu Laurila totesi että talous ymmärretään usein niin että se keskittyy rahaan tai \"bisnekseen\", mutta todellisuudessa se on ihmisten preferenssien ja ennen kaikkea ajankäytön tutkimista.\n" +
            "\n" +
            "Nokkelimmat pokkelimmat tietenkin toteavat että aika on rahaa, ja siten näillä näkökulmilla ei lopulta ole kovin paljoa eroa. Eikä olekaan.\n" +
            "\n" +
            "Yksi hieman itseäni häirinneistä näkökulmista tähän pikkiriikkisen viruksen aiheuttamaan maailmanmyllerrykseen on ollut puhetapa, jossa kysellään, mennäänkö talous vai terveys edellä. Kuten olen aikaisemmin joskus todennut, jos minulla olisi tarpeeksi suuri pyssy, korjaisin sillä sosiaalisia ja epistemologisia ongelmia. Tähän ongelmaan ei taida olla tarpeeksi suurta pyssyä kenellekään.\n" +
            "\n" +
            "Usein esitetään että esimerkiksi taantumasta tai työttömyydestä huolestuvat tahot ovat tosiasiassa vain suuryritysten yms asialla. Toivon että tämä nykyinen kriisitilanne avaisi ihmisille asian todellisen laidan. Valitettavasti elän itse kuplassa, jossa siisteissä, usein akateemisissa töissä työskentelevät ihmiset kokevat tämän tilanteen lähinnä vähän vaivalloisena, kun joutuu tekemään etätöitä tai kun lapset ovat kotona eivätkä koulussa. Nämä samaiset ihmiset edelleen kuvittelevat että talouden valtaisa notkahdus tässä on vaan pikkuinen näpäytys ahneille kapitalisteille, näpäytys, jonka nämä ovat ansainneet, ja josta näkyy vieläpä se hyvä asia että ihmiset ovat vähentäneet lentämistä ja autoilua niin paljon että paikoin ilmanlaatu on parantunut huimasti ja hiilidioksidipäästöt jopa romahtaneet.\n" +
            "\n" +
            "Avarakatseisemmat näkevät ehkä sen \"hieman kiusallisen\" seurauksen, että esimerkiksi ravintola-alalla ja monilla muilla vastaavilla palvelualoilla kysyntä, ja siten kassavirta, on pudonnut käytännössä nollaan. Tästä kärsivät pienyrittäjät ja jo valmiiksi epävarmoissa tilanteissa olevat työntekijät.\n" +
            "\n" +
            "Öljyn hinta putosi pari viikkoa sitten paikoin negatiiviseksi. Tämä ei tietenkään tarkoittanut (yleisestiottaen) sitä, että kun tilaat öljyä niin sinulle maksetaan sen vastaanottamisesta, vaikka toki tietyssä mielessä näinkin kävi. Kyse oli käytännössä etupäässä siitä, että monet öljyä tilanneet tahot olivat valmiita maksamaan siitä, että heidän ei tarvitse ottaa tilaustaan vastaan, kun varastot olivat täynnä. Öljyn varastoiminen kun ei ole ilmaista sekään.\n" +
            "\n" +
            "Näin viime viikon aikana muutamia varsin järjettömiä puheenvuoroja tästä ja siitä miten \"kapitalismi ei toimi\", koska eihän nyt minkään asian hinta voi tällä lailla muuttua negatiiviseksi. En nyt ala niitä ruotimaan, mutta tuon tässä esiin sen, miten erikoisella tavalla ihmisten arjessa muodostama intuitio toimii ja miten paljon ns arkiajattelusta yritetään väenväkisin vääntää selitysmalleja milloin millekin asialle.\n" +
            "\n" +
            "Tilanne on sama myös niiltä osin kuin tulee epidemologiaan ja viruksen käyttäytymiseen. Dunning-Kruger- varoittimeni sanoo että siitä minun ei pidä sanoa mitään, mutta en aiokaan analysoida käytössä olevia malleja sen mukaan että ovatko ne oikeita tai vääriä. Sen sijaan olen tehnyt havainnon että mallien ja niiden pohjalta tehtyjen päätösten kritiikki perustuu todella pitkälti poliittisiin kantoihin.\n" +
            "\n" +
            "Suomen valtakunnantason polarisaatio on onneksi vähäisempää kuin olen kuvitellut. Harvoin nostan hattua Jussi Halla-aholle -- olen näin tehnyt pariin otteeseen koko sinä aikana kun olen hänen olemassaolostaan ollut tietoinen, ja se aika on jo reilusti yli vuosikymmen -- mutta tässä kohtaa teen niin. Katsoin joitain päiviä sitten A-studiota, tai mikä se nyt nykyään onkaan (näin alas olen vajonnut, tiedän) ja siinä oli puoluejohtajia tai varajohtajia juttelemassa toimenpiteistä. Vaikka Halla-aho tietysti oppositiojohtajan ominaisuudessa oli velvoitettu kritisoimaan hallitusta joiltain osin, oli hänen puheenpartensa harvinaisen vähän polarisoivaa eikä hän tuntunut tekevän monen muun populistin tapaan viruksesta ideologista kysymystä.\n" +
            "\n" +
            "USA:ssa käytävää \"dialogia\" muutamasta eri lähteestä seuranneena (kaikkein törkyisimpiä avoviemäreitä en sentään siivilöi) totean että onneksi emme ole sellaisessa polarisaation vaiheessa. Järkevinä pitämäni \"liberaalit\" amerikkalaiset jakavat toinen toistaan alarmistisempia juttuja sosiaalisessa mediassa, syyttävät konservatiiveja (tapansa mukaan) vajaaälyisiksi ja mielisairaiksi, ja konservatiivisemmat taas... No, siellä itse asiassa kirjo on laajempaa. Näkemykset vaihtelevat melkein järkevästä (taloudelliset ja terveydelliset haitat suluista ovat pahemmat kuin viruksesta; tämä on totta, mutta harhaanjohtavasti sanottu) psykofarmakologista interventiota vaativiin (virusta ei ole olemassakaan, vaan kyse on liberaalien vallankaappausyrityksestä).\n" +
            "\n" +
            "Koska yksi tutkimistani matematiikan osa-alueista on optimointi, totean että harhaanjohtavaa tai ei, on totta että pisteittäisestä tilanteesta jossa sulkutoimien aiheuttama marginaalinen haitta on suurempi kuin viruksen aiheuttama marginaalinen haitta, voidaan päätellä että kaikki sulkutoimet eivät ole tarkoituksenmukaisia. Ihmiset jotka ovat sitä mieltä, ettei ihmishengelle \"saa asettaa mitään hintaa\", puhuvat rikkinäisestä intuitiosta käsin. Osmo Soininvaara kirjoitti jo asiasta peräti kahdesti.  Jos meillä  ylipäätään on budjettirajoite, niin ihmishengelle muodostuu hinta, ja jos tämä hinta päätetään vaan sivuuttaa, niin ihmishenkiä menetetään enemmän sitten kun (toisten) rahat loppuvat.\n" +
            "\n" +
            "Suomessa on yllättävän vähän käyty keskustelua tästä aspektista. Kuten Soininvaara totesi, aihe on lähestulkoon tabu. Ja kuitenkin, mitä vähemmän asiasta todella väännetään poliittisesti, sitä enemmän päätöksiä tehdään ilman mitään vastuuta tai kriteeriä jota vasten niitä voisi arvioida. Kun julkisuudessa  keksitytään ainoastaan yhden ihmisryhmän terveyteen tai ainoastaan yhteen mekanismiiin, se, mikä jää kokonaan huomiotta on ne asiat joista luovutaan jotta saadaan pelastettua ne muutamat henget. Ja niiden asioiden joukossa on vääjäämättä jonkun muun henki.\n" +
            "\n" +
            "Näin sellaisen argumentin viime viikolla, että näitä muita ihmisiä ja muita kustannuksia ei tule huomioida koska ne eivät ole \"todellisia\" vaan \"mahdollisia\". Mutta tämä argumentti on sisäisesti epäkoherentti. Suomessa on kuollut koronaan tätä kirjoittaessa virallisten lukujen mukaan 240 ihmistä. Tämä luku on alhaisempi kuin normaali vuosittainen kausi-influenssan kuolleisuus. Tämä on tietenkin hyvä asia, ja varovaisuusperiaate on mielekäs lähtökohta. Sitä ei voi kuitenkaan loputtomiin jatkaa.\n" +
            "\n" +
            "Nyt olen myös nähnyt puheenvuoroja, joiden mukaan mitään helpotuksia rajoituksiin ei pitäisi tehdä, koska kuolleisuus saattaa nousta; Tätä ovat esittäneet jopa tarkalleen samat ihmiset jotka esittivät edellä mainitun argumentin. Näen itse tässä taustalla keskeisenä ongelmana haluttomuuden ja kyvyttömyyden kvantifioida asioita. Me voimme tietenkin aina olla väärässä kun teemme niin, mutta jos emme tee minkäänlaista kvantitatiivista analyysia asiasta, päädymme tekemään päätöksiä joiden seuraukset ovat kuitenkin jälkikäteen kvantifioitavissa mutta täysin satunnaisia ja vailla minkäänlaista kykyä jälkeen päin arvioida olimmeko oikeassa vai väärässä.\n" +
            "\n" +
            "Päättäjille tämä tietysti sopii jos ihmiset ostavat sen ajatuksen että \"teimme parhaamme\" joten lopputulos oli ns. korkeammassa kädessä. Jos toimisimme kvantitatiivisten mallien perusteella -- kuten vaikkapa Saksassa näytetään toimittavan -- lopputuloksen voisi todeta olleen eri kuin malli ennustaa, ja mallia voitaisiin ehkä parantaa. Siinä olisi se \"kiusallinen\" aspekti, että päättäjä joka on päättänyt toimia mallin ennusteen mukaisesti, joutuisi joidenkin mielestä huonoon valoon kun luotti \"väärään\" malliin.\n" +
            "\n" +
            "Tämä onkin sukua sille ajattelulle, että väärässäoleminen ei haittaa kunhan sitä ei myönnä eikä anna muille mahdollisuutta arvioida sitä oliko oikeassa vai väärässä. Kyseinen ajattelu on äärimmäisen vahingollista. Tästä syystä olen pidättäytynyt pääsääntöisesti kritisoimasta niitä jotka esittävät erilaisia malleja, kunhan he eivät ole esittäneet niitä \"itsestäänselvyyksinä\". Elämme perustavanlaatuisten epävarmuuksien kanssa juuri nyt. Kuvitelma että voisimme saada varmuuden sen paremmin valitsemalla jonkun johon luottaa kuin vetämällä äärimmäisyyksiin kaikki toimenpiteet, on harhakuvitelma, katsoi sitä mistä suunnasta tahansa.\n" +
            "\n" +
            "Ihmiset kaippavat varmuutta. Siksi vallassaolevien päättäjien suosio kasvaa kriiseissä, ja erityisesti ns kovaotteisten päättjien suosio kasvaa. Olikin avartavaa huomata miten hanakasti kritiikki on kohdistunut kaikkiin rajoistusten purkamisiin, ja miten herkästi päättäjiä on syytetty \"holttittomuudesta\" !!!\n" +
            "\n" +
            "Toimiiko jos lisätään vielä vähän?\n" +
            "\n" +
            "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Sinänsä taloudellinen toimeliaisuus on vain yksi osa ihmisten hyvinvointia ja yhteiskunnan toimintaa, mutta sen merkitystä usein vähätellään tavoilla joka ei oikein kestä tarkempaa tarkastelua. Ei ole tavatonta, että leppoisan älyllisessä, siistissä sisätyössä työskentelevä downshiftaaja kritisoi \"rahan valtaa\" ja ihmettelee miksi muut eivät elä kuin hän, rennosti ja \"rahasta piittaamatta\". Mediassa ja päivänpolitiikassa pyöriteltävät aiheet vaikuttavat helposti pikkumaisilta, ja sellaisiksi ne leimaantuvatkin kun puhetapa ottaa vallan.\n" +
            "\n" +
            "Sinänsä taloudellinen toimeliaisuus on vain yksi osa ihmisten hyvinvointia ja yhteiskunnan toimintaa, mutta sen merkitystä usein vähätellään tavoilla joka ei oikein kestä tarkempaa tarkastelua. Ei ole tavatonta, että leppoisan älyllisessä, siistissä sisätyössä työskentelevä downshiftaaja kritisoi \"rahan valtaa\" ja ihmettelee miksi muut eivät elä kuin hän, rennosti ja \"rahasta piittaamatta\". Mediassa ja päivänpolitiikassa pyöriteltävät aiheet vaikuttavat helposti pikkumaisilta, ja sellaisiksi ne leimaantuvatkin kun puhetapa ottaa vallan.  \n" +
            "\n" +
            "Raha tulee pankista, ja keskuspankki lainaa rahaa ilmaiseksi pankille joka sitten tyrkyttää sitä ihmisille. Tämä on tietenkin totta prima facie. Yrittäessään systeeminäkökulman avartamista itselleen, tilannetta analysoiva idealisti -- vaikka tämä karakterisointi onkin vähän väärä -- sitten liimaa päälle koko joukon erilaisia sarjakuvamaisia uhkakuvia, kuten luonnon raiskaamista, eläinten kaltoinkohtelua jne, ja laiskana ihmisenä niputtaa kaiken tämän \"kapitalistisen järjestelmän\" väistämättömäksi tuotteeksi. Siinä onkin sitten jo hyvä taputella tuon samaisen paholaisen tuottaman järjestelmän lihottamaa pötsiä itsetyytyväisenä ja uskoa tietävänsä paremmin.\n" +
            "\n" +
            "Todellisuus on kuitenkin olemassa tämän kuplan ulkopuolella. Maanviljelijä kylvää pellot keväällä ja niittä viljan loppukesästä. Tähkäpäistä jauhetaan myllyssä jauhoa ja hiusverkkoon pukeutunut leipuri sen leipoo, oli sitten kyse höttöisestä vehnästä tai tummasta kokojyvästä jota mutustellaan paksusuolen syövän pelossa.\n" +
            "\n" +
            "Karuinta tässä todellisuudessa tietenkin on, että ei oikeastaan ole mitään systeemiä. Ei ole isoveljeä joka oikeasti valvoisi. Terence McKennan sanoin \"The real truth that dares not speak its name is that no one is in control\". Kukaan ei istu puikoissa, valvomo on tyhjä, eikä matrixin keskellä ole salaista huonetta jossa istuu kaiken suunnitellut arkkitehti.\n" +
            "\n" +
            "Sarjakuvamainen käsitys systeemistä, oli kyse sitten pahasta hallituksesta joka yrittää kontrolloida meitä taudin varjolla tai kapitalistisesta salaliitosta, joka houkuttelee ihmiset oravanpyörään tuottamaan lisää kuvitteellista rahaa miljardöörien pohjattomaan kirstuun, on vain lohduttava valhe jota kerromme itsellemme. Evoluutioantropologi Elaine Morgania löyhästi siteeraten, tutkiessamme ihmisten muodostamia yhteiskuntia vastataksemme  kysymykseen \"Mitä ihmiset tahtovat?\", ainoa löytämämme vastaus tuntuu olevan \"lisää\".  Kun kädellinen nappaa kiinni herkusta, se ei päästä irti. Legenda kertoo että apinan voi pyydystää niin että laittaa häkkiin banaanin siten, että se ei mahdu häkin kaltereiden välistä ulos. Kun apina tarraa banaaniin kiinni, se ei saa enää kättään häkistä ulos ja näin se jää vangiksi, sillä se ei osaa irrottaa saaliistaan.\n" +
            "\n" +
            "Suomen valtakunnantason polarisaatio on onneksi vähäisempää kuin olen kuvitellut. Harvoin nostan hattua Jussi Halla-aholle -- olen näin tehnyt pariin otteeseen koko sinä aikana kun olen hänen olemassaolostaan ollut tietoinen, ja se aika on jo reilusti yli vuosikymmen -- mutta tässä kohtaa teen niin. Katsoin joitain päiviä sitten A-studiota, tai mikä se nyt nykyään onkaan (näin alas olen vajonnut, tiedän) ja siinä oli puoluejohtajia tai varajohtajia juttelemassa toimenpiteistä. Vaikka Halla-aho tietysti oppositiojohtajan ominaisuudessa oli velvoitettu kritisoimaan hallitusta joiltain osin, oli hänen puheenpartensa harvinaisen vähän polarisoivaa eikä hän tuntunut tekevän monen muun populistin tapaan viruksesta ideologista kysymystä.\n" +
            "\n" +
            "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Koronaviruksiin kuuluvan Sars-Cov-2- viruksen ja sen aiheuttaman Covid-19- sairauden varjo tulee olemaan pitkä, ihan riippumatta siitä, miten pandemiaksi yltynyt sairaus etenee, kuinka paljon se tappaa jne. Vaikka tautiin keksittäisiin parantava lääkitys tai rokote huomenna, jo nyt toteutettujen sulkujen ja rajoitusten taloudelliset vaikutukset tulevat olemaan useita prosentteja BKT:sta.\n" +
            "\n" +
            "Sinänsä taloudellinen toimeliaisuus on vain yksi osa ihmisten hyvinvointia ja yhteiskunnan toimintaa, mutta sen merkitystä usein vähätellään tavoilla joka ei oikein kestä tarkempaa tarkastelua. Ei ole tavatonta, että leppoisan älyllisessä, siistissä sisätyössä työskentelevä downshiftaaja kritisoi \"rahan valtaa\" ja ihmettelee miksi muut eivät elä kuin hän, rennosti ja \"rahasta piittaamatta\". Mediassa ja päivänpolitiikassa pyöriteltävät aiheet vaikuttavat helposti pikkumaisilta, ja sellaisiksi ne leimaantuvatkin kun puhetapa ottaa vallan.\n" +
            "\n" +
            "Sinänsä taloudellinen toimeliaisuus on vain yksi osa ihmisten hyvinvointia ja yhteiskunnan toimintaa, mutta sen merkitystä usein vähätellään tavoilla joka ei oikein kestä tarkempaa tarkastelua. Ei ole tavatonta, että leppoisan älyllisessä, siistissä sisätyössä työskentelevä downshiftaaja kritisoi \"rahan valtaa\" ja ihmettelee miksi muut eivät elä kuin hän, rennosti ja \"rahasta piittaamatta\". Mediassa ja päivänpolitiikassa pyöriteltävät aiheet vaikuttavat helposti pikkumaisilta, ja sellaisiksi ne leimaantuvatkin kun puhetapa ottaa vallan.  \n" +
            "\n" +
            "Raha tulee pankista, ja keskuspankki lainaa rahaa ilmaiseksi pankille joka sitten tyrkyttää sitä ihmisille. Tämä on tietenkin totta prima facie. Yrittäessään systeeminäkökulman avartamista itselleen, tilannetta analysoiva idealisti -- vaikka tämä karakterisointi onkin vähän väärä -- sitten liimaa päälle koko joukon erilaisia sarjakuvamaisia uhkakuvia, kuten luonnon raiskaamista, eläinten kaltoinkohtelua jne, ja laiskana ihmisenä niputtaa kaiken tämän \"kapitalistisen järjestelmän\" väistämättömäksi tuotteeksi. Siinä onkin sitten jo hyvä taputella tuon samaisen paholaisen tuottaman järjestelmän lihottamaa pötsiä itsetyytyväisenä ja uskoa tietävänsä paremmin.";

    public static String getBlogPost() {
        return blogPost;
    }

    public static String getHeartOfDarkness() {
        String heartOfDarkness = "";
        try {
            heartOfDarkness = FileManager.readText("test_heart_of_darkness.txt");
        } catch (Exception e) {}
        return heartOfDarkness;
    }

    public static String getRepetitiveText() {
        String string = "";
        for (int i = 0; i < 1000; i++) {
            string += "Tässä olisi vähän tekstiä, toistetaan huomattavan monta kertaa samanlaisena. ";
        }
        return string;
    }


}
